### ISSUE TITLE
Kontrola úkolu: vizitka

### ISSUE THREAD

**Issue by LenkaVer** [karolinavaitt/PROJEKT-Vizitka#1]
Ahoj Karolíno,
dobrá práce.
Jen pár drobností: margin nastavuješ dvakrát (pomocí souhrnného margin a margin-top), stačí napsat ten souhrnný margin: 150px auto 0 auto.
Nefunguje hover na odkazech, pomoci by mělo, když umažeš tu mezeru mezi třídou a :hover/:active.

**Comment by karolinavaitt** [comment]
Ahoj Lenko,
díky, taková "blbost", já se s tím hover trápila :-) Vše je opraveno.

**Comment by LenkaVer** [comment]
Ahoj,
to je klasika, že se přehlídne čárka, mezera atd. :)
Super!
